spring:
  application:
    name: system-service
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.101.65:3306/xcplus_system?serverTimezone=UTC&userUnicode=true&useSSL=false&
#    username: root
#    password: mysql

  cloud:
    nacos:
      server-addr: 192.168.101.65:8848
      config: #配置文件相关配置
        namespace: ${spring.profiles.active}
        group: irv-process-project
        file-extension: yaml
        refresh-enabled: true
  profiles:
    active: irv # 环境名
# 日志文件配置路径
logging:
  config: classpath:log4j2-dev.xml


